qsub -v "args= --output_dir=outputs/imagenet/gm_gradmax_late_40  --config=growneuron/imagenet/configs/grow_all_at_once_resnet_late_40.py --config.grow_type=add_gradmax" -N gm_gradmax_late_40 -o ../outputs/imagenet/gm_gradmax_late_40/gm_gradmax_late_40.o grow_template.sh
qsub -v "args= --output_dir=outputs/imagenet/gm_firefly_late_40  --config=growneuron/imagenet/configs/grow_all_at_once_resnet_late_40.py --config.grow_type=add_firefly" -N gm_firefly_late_40 -o ../outputs/imagenet/gm_firefly_late_40/gm_firefly_late_40.o grow_template.sh
qsub -v "args= --output_dir=outputs/imagenet/gm_random_late_40 --config=growneuron/imagenet/configs/grow_all_at_once_resnet_late_40.py --config.grow_type=add_random" -N gm_random_late_40 -o ../outputs/imagenet/gm_random_late_40/gm_random_late_40.o grow_template.sh

qsub -v "args= --output_dir=outputs/imagenet/gm_gradmax_late_45  --config=growneuron/imagenet/configs/grow_all_at_once_resnet_late_40.py --config.grow_type=add_gradmax --config.updater.start_iteration=81000" -N gm_gradmax_late_45 -o ../outputs/imagenet/gm_gradmax_late_45/gm_gradmax_late_45.o grow_template.sh
qsub -v "args= --output_dir=outputs/imagenet/gm_firefly_late_45  --config=growneuron/imagenet/configs/grow_all_at_once_resnet_late_40.py --config.grow_type=add_firefly --config.updater.start_iteration=81000" -N gm_firefly_late_45 -o ../outputs/imagenet/gm_firefly_late_45/gm_firefly_late_45.o grow_template.sh
qsub -v "args= --output_dir=outputs/imagenet/gm_random_late_45 --config=growneuron/imagenet/configs/grow_all_at_once_resnet_late_40.py --config.grow_type=add_random --config.updater.start_iteration=81000" -N gm_random_late_45 -o ../outputs/imagenet/gm_random_late_45/gm_random_late_45.o grow_template.sh

#qsub -v "args= --output_dir=outputs/imagenet/gm_gradmax_late_52  --config=growneuron/imagenet/configs/grow_all_at_once_resnet_late_40.py --config.grow_type=add_gradmax --config.updater.start_iteration=99000" -N gm_gradmax_late_52 -o ../outputs/imagenet/gm_gradmax_late_52/gm_gradmax_late_52.o grow_template.sh
#qsub -v "args= --output_dir=outputs/imagenet/gm_firefly_late_52  --config=growneuron/imagenet/configs/grow_all_at_once_resnet_late_40.py --config.grow_type=add_firefly --config.updater.start_iteration=99000" -N gm_firefly_late_52 -o ../outputs/imagenet/gm_firefly_late_52/gm_firefly_late_52.o grow_template.sh
#qsub -v "args= --output_dir=outputs/imagenet/gm_random_late_52 --config=growneuron/imagenet/configs/grow_all_at_once_resnet_late_40.py --config.grow_type=add_random --config.updater.start_iteration=99000" -N gm_random_late_52 -o ../outputs/imagenet/gm_random_late_52/gm_random_late_52.o grow_template.sh
#
#qsub -v "args= --output_dir=outputs/imagenet/gm_gradmax_late_58  --config=growneuron/imagenet/configs/grow_all_at_once_resnet_late_40.py --config.grow_type=add_gradmax --config.updater.start_iteration=113000" -N gm_gradmax_late_58 -o ../outputs/imagenet/gm_gradmax_late_58/gm_gradmax_late_58.o grow_template.sh
#qsub -v "args= --output_dir=outputs/imagenet/gm_firefly_late_58  --config=growneuron/imagenet/configs/grow_all_at_once_resnet_late_40.py --config.grow_type=add_firefly --config.updater.start_iteration=113000" -N gm_firefly_late_58 -o ../outputs/imagenet/gm_firefly_late_58/gm_firefly_late_58.o grow_template.sh
#qsub -v "args= --output_dir=outputs/imagenet/gm_random_late_58 --config=growneuron/imagenet/configs/grow_all_at_once_resnet_late_40.py --config.grow_type=add_random --config.updater.start_iteration=113000" -N gm_random_late_58 -o ../outputs/imagenet/gm_random_late_58/gm_random_late_58.o grow_template.sh

