qsub -v "args=  --output_dir=outputs/cifar10/24570_single/gm_gradmax_cifar --config=growneuron/cifar/configs/grow_all_at_once_28_5_single.py --config.grow_type=add_gradmax --config.updater.start_iteration=24570 --config.dataset=cifar10" -N gm_gradmax_cifar_single_24 -o ../outputs/cifar10/24570_single/gm_gradmax_cifar/gm_gradmax_cifar.o grow_template_cifar.sh
qsub -v "args=  --output_dir=outputs/cifar10/24570_single/gm_firefly_cifar --config=growneuron/cifar/configs/grow_all_at_once_28_5_single.py --config.grow_type=add_firefly --config.updater.start_iteration=24570 --config.dataset=cifar10" -N gm_firefly_cifar_single_24 -o ../outputs/cifar10/24570_single/gm_firefly_cifar/gm_firefly_cifar.o grow_template_cifar.sh
qsub -v "args=  --output_dir=outputs/cifar10/24570_single/gm_random_cifar --config=growneuron/cifar/configs/grow_all_at_once_28_5_single.py --config.grow_type=add_random --config.updater.start_iteration=24570 --config.dataset=cifar10" -N gm_random_cifar_single_24 -o ../outputs/cifar10/24570_single/gm_random_cifar/gm_random_cifar.o grow_template_cifar.sh

qsub -v "args=  --output_dir=outputs/cifar10/24570_single_2/gm_gradmax_cifar --config=growneuron/cifar/configs/grow_all_at_once_28_5_single.py --config.seed=2 --config.grow_type=add_gradmax --config.updater.start_iteration=24570 --config.dataset=cifar10" -N gm_gradmax_cifar_single_24_2 -o ../outputs/cifar10/24570_single_2/gm_gradmax_cifar/gm_gradmax_cifar.o grow_template_cifar.sh
qsub -v "args=  --output_dir=outputs/cifar10/24570_single_2/gm_firefly_cifar --config=growneuron/cifar/configs/grow_all_at_once_28_5_single.py --config.seed=2 --config.grow_type=add_firefly --config.updater.start_iteration=24570 --config.dataset=cifar10" -N gm_firefly_cifar_single_24_2 -o ../outputs/cifar10/24570_single_2/gm_firefly_cifar/gm_firefly_cifar.o grow_template_cifar.sh
qsub -v "args=  --output_dir=outputs/cifar10/24570_single_2/gm_random_cifar --config=growneuron/cifar/configs/grow_all_at_once_28_5_single.py --config.seed=2 --config.grow_type=add_random --config.updater.start_iteration=24570 --config.dataset=cifar10" -N gm_random_cifar_single_24_2 -o ../outputs/cifar10/24570_single_2/gm_random_cifar/gm_random_cifar.o grow_template_cifar.sh
#
qsub -v "args=  --output_dir=outputs/cifar10/24570_single_3/gm_gradmax_cifar --config=growneuron/cifar/configs/grow_all_at_once_28_5_single.py --config.seed=3 --config.grow_type=add_gradmax --config.updater.start_iteration=24570 --config.dataset=cifar10" -N gm_gradmax_cifar_single_24_3 -o ../outputs/cifar10/24570_single_3/gm_gradmax_cifar/gm_gradmax_cifar.o grow_template_cifar.sh
qsub -v "args=  --output_dir=outputs/cifar10/24570_single_3/gm_firefly_cifar --config=growneuron/cifar/configs/grow_all_at_once_28_5_single.py --config.seed=3 --config.grow_type=add_firefly --config.updater.start_iteration=24570 --config.dataset=cifar10" -N gm_firefly_cifar_single_24_3 -o ../outputs/cifar10/24570_single_3/gm_firefly_cifar/gm_firefly_cifar.o grow_template_cifar.sh
qsub -v "args=  --output_dir=outputs/cifar10/24570_single_3/gm_random_cifar --config=growneuron/cifar/configs/grow_all_at_once_28_5_single.py --config.seed=3 --config.grow_type=add_random --config.updater.start_iteration=24570 --config.dataset=cifar10" -N gm_random_cifar_single_24_3 -o ../outputs/cifar10/24570_single_3/gm_random_cifar/gm_random_cifar.o grow_template_cifar.sh




